### ISSUE TITLE
"pip install transgan-pytorch " not working

### ISSUE THREAD

**Issue by Pranaykhariwal** [rish-16/TransGAN-PyTorch#1]
Hi , Can u please guide on how to run your code ? On running test.py ,  it gives the following error 

"cannot import name 'TransGAN' from 'transgan_pytorch'"

on running pip install , it gives the following error

[8]
pip install transgan-pytorch
ERROR: Could not find a version that satisfies the requirement transgan-pytorch (from versions: none)
ERROR: No matching distribution found for transgan-pytorch

**Comment by rish-16** [comment]
Hi, thanks for checking it out.

It's still a work in progress. I took it down for maintenance.
